apache/maven-gpg-plugin

src/main/java/org/apache/maven/plugins/gpg/GpgVersion.java, src/test/java/org/apache/maven/plugins/gpg/GpgVersionConsumerTest.java
Provides an refactored implementation of GpgVersion to address [MGPG-81](https://issues.apache.org/jira/projects/MGPG/issues/MGPG-81).
The parsing logic is being moved from "GpgVersion#compareTo" to "GpgVersion#parse" to throw IllegalArgumentException in a semantically correct way.
=> [MGPG-81] check format in constructor

src/main/java/org/apache/maven/plugins/gpg/GpgVersion.java, src/test/java/org/apache/maven/plugins/gpg/GpgVersionConsumerTest.java, src/test/java/org/apache/maven/plugins/gpg/GpgVersionTest.java
Provides an implementation of GpgVersion#equals andGpgVersion#hashCode to address [MGPG-80](https://issues.apache.org/jira/projects/MGPG/issues/MGPG-80).
"GpgVersion#equals" is implemented by utilizing "GpgVersion#compareTo".
=> [MGPG-80] implement GpgVersion equality in adherence to comparibility

src/it/sign-release-with-excludes/pom.xml, src/it/sign-release-with-excludes/verify.bsh, src/main/java/org/apache/maven/plugins/gpg/GpgSignAttachedMojo.java
Fixes [MGPG-66](https://issues.apache.org/jira/projects/MGPG/issues/MGPG-66) by adding a check if files match the exclude patterns.
=> [MGPG-66] fix handling of excluded files

pom.xml, src/it/sign-release-without-passphrase/invoker.properties, src/it/sign-release-without-passphrase/pom.xml, src/it/sign-release-without-passphrase/verify.bsh, src/main/java/org/apache/maven/plugins/gpg/GpgSigner.java, src/test/java/org/apache/maven/plugins/gpg/it/BuildResult.java, src/test/java/org/apache/maven/plugins/gpg/it/GpgSignAttachedMojoIT.java, src/test/java/org/apache/maven/plugins/gpg/it/InvokerTestUtils.java, src/test/resources/gnupg/gpg-agent.conf, src/test/resources/it/settings.xml, src/test/resources/it/sign-release-without-passphrase-interactive/pom.xml
Fixes [MGPG-79](https://issues.apache.org/jira/projects/MGPG/issues/MGPG-79) by using the default "pinentry-mode" if no passphrase for the GPG key is given.
Only in case a passphrase for the GPG key is given and shall be passed to GPG via stdin, the "pinentry-mode" is set to "loopback".
Additionally the "--batch" option is set as long as Maven is running in "non-interactive" mode to prevent other GPG input prompts (e.g. prompting to overwrite an already existing signature file), which would cause the command to hang indefinitely.
=> [MGPG-79] fix handling of external pinentry programs in case the passphrase is not given

src/main/java/org/apache/maven/plugins/gpg/FilesCollector.java
Testing whether the CI is broken. Nothing in this PR should fail any test. 
@timtebeek
=> javadoc nits

src/main/java/org/apache/maven/plugins/gpg/AbstractGpgMojo.java, src/main/java/org/apache/maven/plugins/gpg/GpgSigner.java, src/main/java/org/apache/maven/plugins/gpg/GpgVersionParser.java
Continuation of https://issues.apache.org/jira/browse/MNG-6829
Review requested of @elharo
Use this link to re-run the recipe: https://public.moderne.io/recipes/org.openrewrite.java.migrate.apache.commons.lang.IsNotEmptyToJdk?organizationId=QXBhY2hlIE1hdmVu
=> [MNG-6829] Replace StringUtils#isEmpty(String) and #isNotEmpty(String)

src/main/java/org/apache/maven/plugins/gpg/GpgSigner.java
When passphrase is being supplied with `--passphrase-fd 0`.
---
https://issues.apache.org/jira/browse/MGPG-99
=> [MGPG-99] Make sure newline is added to input stream

src/it/sign-release-with-excludes/verify.groovy, src/main/java/org/apache/maven/plugins/gpg/SignAndDeployFileMojo.java
It was validating POMs as "Maven2". These POMs should be handled as "new projects" and they must have strict validation in effect instead. Still, given "strict" validation is a moving target (it depends on currently running Maven version), we need to factor in Maven4 as well. Once beta, Maven4 should be added to build matrix. Currently was running locally the build with latest alpha-13 SNAPSHOT (it went OK) that showed one IT that was sensitive to it, fixed in this PR as well.
---
https://issues.apache.org/jira/browse/MGPG-110
=> [MGPG-110] SignAndDeployFileMojo validation is off

src/main/java/org/apache/maven/plugins/gpg/AbstractGpgMojo.java, src/main/java/org/apache/maven/plugins/gpg/SignAndDeployFileMojo.java
The RemoteRepository was "bare", it has to be equipped with AuthenticationSelector to be able to perform authenticated deploys. Also, remove "layout" as since Maven 3.0 there is no other layout than "default".
Also, a bit of tidy up, layout is deprecated in Maven3 and is unused.
---
https://issues.apache.org/jira/browse/MGPG-113
=> [MGPG-113] SignAndDeployFileMojo results in 401

src/main/java/org/apache/maven/plugins/gpg/BcSigner.java
This insanely huge key size is mentioned as some extreme example on page https://wiki.gnupg.org/LargeKeys
---
https://issues.apache.org/jira/browse/MGPG-114
=> [MGPG-114] Allow max key size of 16KB

src/main/java/org/apache/maven/plugins/gpg/AbstractGpgSigner.java, src/main/java/org/apache/maven/plugins/gpg/BcSigner.java, src/main/java/org/apache/maven/plugins/gpg/GpgSignAttachedMojo.java, src/main/java/org/apache/maven/plugins/gpg/GpgSigner.java, src/main/java/org/apache/maven/plugins/gpg/SignAndDeployFileMojo.java
Just show some usable feedback _which key_ is used to sign.
---
https://issues.apache.org/jira/browse/MGPG-115
=> [MGPG-115] Show more info about key used to sign

src/main/java/org/apache/maven/plugins/gpg/BcSigner.java
Allow 64K files as well, as this may be "ring" (collection of keys) as well.
---
https://issues.apache.org/jira/browse/MGPG-116
=> [MGPG-116] Up max key file size to 64K

src/main/java/org/apache/maven/plugins/gpg/BcSigner.java
Make sure is gone from heap once not needed.
---
https://issues.apache.org/jira/browse/MGPG-117
=> [MGPG-117]  Improve passphrase handling

src/it/sign-release-best-practices-fail/invoker.properties, src/it/sign-release-best-practices-fail/pom.xml, src/it/sign-release-best-practices-fail/verify.groovy, src/it/sign-release-best-practices/invoker.properties, src/it/sign-release-best-practices/pom.xml, src/it/sign-release-best-practices/verify.groovy, src/it/sign-release/verify.groovy, src/main/java/org/apache/maven/plugins/gpg/AbstractGpgMojo.java
As currently due defaulted values it would always fail, unless user explicitly re-configures plugin. So, do not set "default value" on mojo level, instead handle it programmatically, when bestPractices is not set. Added ITs for "bestPractices", one for success and one for failure. 
---
https://issues.apache.org/jira/browse/MGPG-125
=> [MGPG-125] Fix "bestPractices"

src/main/java/org/apache/maven/plugins/gpg/FilesCollector.java
Sigstore uses ".sigstore.json" extension in all our plugins, ".sigstore" is no longer used. 
Context: https://github.com/sigstore/sigstore-maven-plugin/blob/main/src/main/java/dev/sigstore/plugin/SigstoreSignAttachedMojo.java#L47
This change is consistent across java clients ([gradle](https://github.com/sigstore/sigstore-java/blob/main/sigstore-gradle/sigstore-gradle-sign-base-plugin/src/main/kotlin/dev/sigstore/sign/SigstoreSignature.kt#L28)) and language clients ([python](https://github.com/sigstore/sigstore-python/blob/53c39d9ff48bee22b0da02e5ef63f23968bc65db/sigstore/_cli.py#L497))
----
Following this checklist to help us incorporate your contribution quickly and easily:
before you start working on it). Trivial changes like typos do not require a JIRA issue. Your pull request should …
=> [MGPG-130] - Update sigstore extension to ".sigstore.json"

src/main/java/org/apache/maven/plugins/gpg/AbstractGpgMojo.java
Currently AbstractGpgMojo has a fixed set of supported signers (and how they are constructed), it would be good to allow extensions (e.g. Tycho is also using AbstractGpgMojo) to possibly override that aspect.
This extracts the creation of the signer into a (protected) method so different types or alternative implementations can be used.
Following this checklist to help us incorporate your contribution quickly and easily:
before you start working on it). Trivial changes like typos do not require a JIRA issue. Your pull request should
address just this issue, without pulling in other changes.
with the appropriate JIRA issue. Best practice is to use the JIRA issue title in the pull request title and in the
first line of the commit message.
request automatically.
If your pull request is about …
=> [MGPG-135] Support Overriding / Enhance the signer in AbstractGpgMojo

pom.xml
This is really just "build time" as at runtime it uses given Maven version artifacts anyway.
---
https://issues.apache.org/jira/browse/MGPG-140
=> [MGPG-140] Update Maven to 3.9.9

src/main/java/org/apache/maven/plugins/gpg/GpgSigner.java, src/main/java/org/apache/maven/plugins/gpg/SignAndDeployFileMojo.java
The MGPG-138 also updated plexus-utils to 4.0.1 and plexus-xml to 3.0.1.
---
https://issues.apache.org/jira/browse/MGPG-141
=> [MGPG-141] Remove use of deprecated classes

src/site/fml/faq.fml
=> Add FAQ for "no pinentry" issue

pgp-keys-map.list, pom.xml, src/test/java/org/apache/maven/plugins/gpg/it/BcSignArtifactIT.java, src/test/java/org/apache/maven/plugins/gpg/it/InvokerTestUtils.java
And related fixes:
* POM add missing deps
* move to Maven 3 p-u, drop p-x
* test: checkstyle fixes
=> Update parent POM to 45
